import Head from "next/head";
import React, { useState } from "react";
import styles from "@/styles/Home.module.css";
import Footer from "@/Components/Footer";
import HeroSection from "@/Components/HeroSection";
import ContentSection from "@/Layouts/ContentSection";
import Packages from "@/Components/Packages";
import AboutSection from "@/Components/AboutSection";
import BookNow from "@/Components/BookNow";
import Commitment from "@/Components/Commitment";
import QASection from "@/Components/QASection";
import Reviews from "@/Components/Reviews";

export default function Home() {
  const scrollToForm = () => {
    const form = document.querySelector("#contact-form");
    form.scrollIntoView({ behavior: "smooth" });
  }

  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [date, setDate] = useState('');
  const [eventType, setEventType] = useState('');
  const [email, setEmail] = useState('');
  const [location, setLocation] = useState('');
  const [time, setTime] = useState('');
  const [textOk, setTextOk] = useState('Yes');
  const [message, setMessage] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    const res = await fetch('/api/send-email', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ name, phone, date, eventType, email, location, time, textOk, message }),
    });
    const data = await res.json();
    console.log(data.message);
  };

  return (
    <>
      <Head>
        <title>Face Painting by Rikki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <HeroSection scroll={scrollToForm} />
        <ContentSection topColor="#de68d6" bottomColor="#de68d6">
          <BookNow scroll={scrollToForm} />
          <Packages scroll={scrollToForm}/>
        </ContentSection>
        <ContentSection topColor="#de68d6" bottomColor="blue">
          <AboutSection scroll={scrollToForm} />
          <Commitment />
          <QASection />
        </ContentSection>


        <ContentSection topColor="blue" bottomColor="#de68d6">
          <Reviews />
        </ContentSection>


        <ContentSection topColor="#de68d6" bottomColor="blue">
          <div className={styles.formHeader}>
            <h1>Get In Touch</h1>
            <p>
              We are available online and over call. Fill out this form below
              and we will get back to you.
            </p>
          </div>

          <form className={styles.form} id="contact-form" onSubmit={handleSubmit}>
            <div className={styles.formContainer}>
              <div className={styles.formLeft}>
                <input
                  type="text"
                  placeholder="Name"
                  className={styles.formInput}
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                />
                <input
                  type="text"
                  placeholder="Phone"
                  className={styles.formInput}
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                />
                <input
                  type="date"
                  className={styles.formInput}
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                />
                <label htmlFor="eventType">What type of event is it?</label>
                <input
                  type="text"
                  placeholder="Event Type"
                  className={styles.formInput}
                  value={eventType}
                  onChange={(e) => setEventType(e.target.value)}
                />
              </div>
              <div className={styles.formRight}>
                <input
                  type="text"
                  placeholder="Email"
                  className={styles.formInput}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
                <input
                  type="text"
                  placeholder="Neighborhood or town"
                  className={styles.formInput}
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                />
                <input
                  type="time"
                  className={styles.formInput}
                  value={time}
                  onChange={(e) => setTime(e.target.value)}
                />
                <label htmlFor="textOk">Is it OK to Text?</label>
                <select
                  id="textOk"
                  className={styles.formInput}
                  value={textOk}
                  onChange={(e) => setTextOk(e.target.value)}
                >
                  <option value="Yes">Yes</option>
                  <option value="No">No</option>
                </select>
              </div>
            </div>
            <textarea
              className={styles.formTextArea}
              placeholder="Message"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
            ></textarea>
            <button className={styles.otherButton} type="submit">
              Get in touch
            </button>
          </form>
          </ContentSection>
      </main>
      <Footer />
    </>
  );
}
